config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'

  root to: 'visitors#index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', :sessions => "sessions", :registrations => 'registrations' }
   #path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :users

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
	find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	TEMP_EMAIL_PREFIX = 'change@me'
	TEMP_EMAIL_REGEX = /\Achange@me/

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :twitter, :linked_in, :google_oauth2]

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_filter :ensure_signup_complete, only: [:new, :create, :update, :destroy]

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)  	
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :linked_in, :google_oauth2].each do |provider|
  	provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    @user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  def index
    @users = User.all
  end
  
  # GET /users/:id.:format
  def show
    # authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user

    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    # Rails.logger.debug 'error'

    if request.patch? && params[:user] #&& params[:user][:email]
      # binding.pry
      if @user.update_attributes(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  def show
    @user = User.find(params[:id])    
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      attr_accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Care Compass"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/_footer.html.erb
<div class="homepage-social-icons">
  <ul>
    <li><%= link_to image_tag('facebook.png', alt: 'Facebook'), 'http://facebook.com' %></li>
    <li><%= link_to image_tag('twitter.png', alt: 'Twitter'), 'http://twitter.com' %></li>
    <li><%= link_to image_tag('google_plus.png', alt: 'Google Plus'), 'http://plus.google.com' %></li>
    <li><%= link_to image_tag('pinterest.png', alt: 'Pinterest'), 'http://pinterest.com' %></li>
    <li><%= link_to image_tag('email.png', alt: 'Email'), '#' %></li>
    <li><%= link_to image_tag('printer.png', alt: 'Printer'), '#' %></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="header-container">
      <div class="first-header-section">
        <div class="header-link-block">
          <%= link_to '#', :class => 'header-link' do %>
            <span class="glyphicon glyphicon-earphone header-phone-icon"></span>
            <span class="header-link-title">1.866.555.5555</span>
          <% end %>
          <%= link_to '#', :class => 'header-link' do %>
            <span class="glyphicon glyphicon-cloud header-live-help-icon"></span>
            <span class="header-link-title">Live Help</span>
          <% end %>
          <%= link_to '#', :class => 'header-link' do %>
            <span class="glyphicon glyphicon-globe header-locale-icon"></span>
            <span class="header-link-title">English</span>
            <span class="glyphicon glyphicon-triangle-bottom header-locale-arrow"></span>
          <% end %>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="second-header-section">
        <div class="navbar-header navbar-header-redefine">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Care Compass', root_path, class: 'navbar-brand navbar-brand-redefine hidden-xs' %>
        </div>

        <div class="explore-view-block col-lg-8 row">
          <div class="explore-block col-lg-6">
            <span>Explore:</span>
            <ul>
              <li><%= link_to 'PLANS', '#', class: 'explore-plans' %></li>
              <li><%= link_to 'PROVIDERS', '#', class: 'explore-providers' %></li>
            </ul>
          </div>

          <div class="view-block col-lg-6">
              <span>View:</span>
              <ul>
                <li><%= link_to 'ALL PLANS', '#', class: 'view-all-plans' %></li>
                <li><%= link_to 'BOOKMARKS', '#', class: 'view-bookmarks' %></li>
              </ul>
              <span class="glyphicon glyphicon-bookmark"></span>
          </div>

        </div>

        <div class="collapse navbar-collapse navbar-collapse-redefine">
          <ul class="navbar-nav-redefine">
            <%= render 'layouts/navigation_links' %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_homepage_content.html.erb
<div class="homepage-content-block">
  <%= yield %>
</div>
<%= render 'users/shared/plan_dialog' %>

app/views/layouts/_homepage_footer.html.erb
<div class="homepage-desc-block row">
	<%= yield :overview %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= full_title(yield(:title)) %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main role="main">
      <%= render 'layouts/messages' %>
      <div class="homepage-wrapper">
        <%= render 'layouts/homepage_content' %>
        <%= render 'layouts/homepage_footer' %>
        <%= render 'layouts/footer' %>
      </div>
    </main>
  </body>
</html>

app/views/plans/index.html.erb
<% content_for :overview do %>
  <div class="col-lg-12 col-sm-12 col-xs-12 footer-overview">
    <h2>Overview of Features</h2>
    <div class="col-lg-12 col-sm-12 col-xs-12">
      <p>As many consumers are unfamiliar with the National Commitee for Quality Assurance (NCQA), first-time users will see a pop-up explaining NCQA scores in their first interface with their Plan View. NCQA scores are the industry stand for evaluating access & quality standards amongst health. In our application, the overal quality score is depicted as a large blue number with preventive, treatment, and consumer satisfaction scores as small red numbers, all of which are displayed in the expanded view to avoid overwhelming the user with excessive numbers in the collapsed view. Once this pop-up is closed, it will not display again for the users at return visits (accomplished via dropping cookies on the user's computer) unless they click on the tool tip question mark icon.</p>
    </div>    
  </div>
<% end %>
<div id="planGoogleMap">
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<div class="shared_links">
	<%= link_to image_tag('facebook-login-button.png', alt: 'Facebook Login Button'), user_omniauth_authorize_path(:facebook) %>
	<%= link_to image_tag('google-plus-login-button.png', alt: 'Google+ Login Button'), user_omniauth_authorize_path(:google_oauth2), style: 'margin-top: 10px' %>
</div>

app/views/users/shared/_plan_dialog.html.erb
<div class="modal fade" id="userPlanDlg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
    <div class="modal-content user-plan-dialog">
    	<div class="modal-header">
	    	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	    	<h1>You may be eligible for a subsidy</br>to help you pay for a marketplace health plan</h1>
    	</div>
    	<div class="modal-body">
				<div>
					<p>Based on your previous answers about household income, you may be eligible for a subsidy to help you pay for your health plan. These subsidies can only be applied to Silver tier plans.</p>
				</div>
				<div>
					<p>Would you like to see these plans first?</p>
				</div>
			</div>
			<div class="modal-footer">
				<%= link_to raw('<span>Yes</span>, show me Silver, subsidy-eligible plans first'), plans_index_path %>
				<%= link_to raw('<span>No</span>, proceed to plans without pre-sorting'), '#' %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<% content_for :overview do %>
  <div class="col-lg-12 col-sm-12 col-xs-12 footer-overview">
    <h2>Overview of Features</h2>
    <div class="col-lg-12 col-sm-12 col-xs-12">
      <p>We support optional sign-up & login through our application along with social media avenues to provide consumers with an easy account creation and login process, after which they will have the ability to save plans, providers, and searches on a personal dashboard and share their preferences with their social network.
      Returning users may also login in order to refer back to their plan's benefits, visualize their selected plan's provider network, and rate plans and/or providers.</p>
    </div>
  </div>
<% end %>

<div class="user-profile-page">
	<div class="user-profile-zipcode">
		<%= link_to 'My Zip Code is [zipcode]', '#' %>
	</div>
	<div class="user-profile-dropdown">
		<%= link_to 'and I\'d like to cover', '#' %>
	</div>
	<div class="dropdown">
	  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
	    Dropdown
	    <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
	    <li><a href="#">me</a></li>
	    <li><a href="#">me & my spouse</a></li>
	    <li><a href="#">me, my spouse, & kids</a></li>
	    <li><a href="#">me & my kids</a></li>
	  </ul>
	</div>
	<div class="user-profile-years">
		<%= link_to 'I\'m [27] years old.', '#' %>
	</div>
	<div class="user-profile-price">
		<%= link_to 'My family makes $[25,000] per year.', '#' %>
	</div>
	<div class="user-profile-household">
		<%= link_to 'There is [1] person in my tax household.', '#' %>
	</div>
	<div class="user-profile-plan">
		<%= link_to 'Please only show me plans with [Doctor or Facility\'s name] in-network*', '#', data: {toggle: "modal", target: "#userPlanDlg"} %>
	</div>
</div>

app/views/visitors/index.html.erb
<% provide(:title, 'Home Page') %>

<% content_for :overview do %>
  <div class="col-lg-12 col-sm-12 col-xs-12 footer-overview">
    <h2>Overview of Features</h2>
    <div class="col-lg-6 col-sm-6 col-xs-12">
      <p>An education section offers definitions of terms & answers to frequently asked questions.
      A cursor hover feature is also present over terms (i.e. Premium, Deductible, etc.) in every application
      screen for quick consumer reference in the user's current page view.</p>
    </div>
    <div class="col-lg-6 col-sm-6 col-xs-12">
      <p>Customers can contact support personnel via phone or in-application messaging for help in navigating the application.
      We support English & Spanish, the first & second national languages. A consumer can also click on Find Local Help for a list of community navigators in their area.</p>
    </div>
  </div>
<% end %>
<div class="homepage-logo-block">
  <div class="homepage-welcome-title text-center">
    <h1>Welcome to CareCompass</h1>
  </div>
  <div class="homepage-logo-title">
    <p>Explore Plans</br>In My Area</p>
  </div>
  <div class="homepage-logo-description row">
    <div class="homepage-logo-desc1 pull-left">
      <p></br>Marketplace</br>Glosssary & FAQ</p>
    </div>
    <div class="homepage-logo-desc2 pull-right">
      <p>Find Local</br>Help For My</br>Plan Search</p>
    </div>
  </div>
</div>

    